apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: bundles-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        DB_USER: "{{ .DB_USER }}"
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        SHOPIFY_API_KEY: "{{ .SHOPIFY_API_KEY }}"
        SHOPIFY_API_SECRET: "{{ .SHOPIFY_API_SECRET }}"
        SHOPIFY_APP_URL: "https://skirmshop.e-dani.com/bundles"
        SHOPIFY_STORE: "ymimst-yh.myshopify.com"
        SHOPIFY_SHOP_DOMAIN: "ymimst-yh.myshopify.com"
  data:
    - secretKey: DB_USER
      remoteRef:
        key: skirmshop/postgres
        property: app-username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: skirmshop/postgres
        property: app-password
    - secretKey: SHOPIFY_API_KEY
      remoteRef:
        key: skirmshop/shopify-bundles
        property: shopify_api_key
    - secretKey: SHOPIFY_API_SECRET
      remoteRef:
        key: skirmshop/shopify-bundles
        property: shopify_api_secret
