apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: brain-relations
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: bundles-brain-relations
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: BRAIN_RELATIONS_API_KEY
      remoteRef:
        key: skirmshop-brain/prod/product-relations
        property: relations_api_key
